# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - webapp-lab-random

on:
  push:
    branches:
      - main
      # Temporarily disabled staging deployment due to identity federation issue
      # - staging
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read # required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: npm install, build
        run: |
          npm install
          npm run build --if-present
         
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: .

  deploy-production:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_97423809BDD846D0A76B0B3BFC35A027 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_F37A58B16D544F19B99C25F8E9715A09 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_9B15030317A34B218C9745750F662EF7 }}

      - name: Deploy to Azure Web App (Production)
        id: deploy-to-production
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'webapp-lab-random'
          slot-name: 'Production'
          package: .

  # Temporarily disabled staging deployment due to identity federation issue
  # Uncomment and configure when identity federation is set up for staging branch
  # deploy-staging:
  #   runs-on: ubuntu-latest
  #   needs: build
  #   if: github.ref == 'refs/heads/staging'
  #   permissions:
  #     id-token: write
  #     contents: read

  #   steps:
  #     - name: Download artifact from build job
  #       uses: actions/download-artifact@v4
  #       with:
  #         name: node-app

  #     - name: Login to Azure
  #       uses: azure/login@v2
  #       with:
  #         client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_97423809BDD846D0A76B0B3BFC35A027 }}
  #         tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_F37A58B16D544F19B99C25F8E9715A09 }}
  #         subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_9B15030317A34B218C9745750F662EF7 }}

  #     - name: Deploy to Azure Web App (Staging)
  #       id: deploy-to-staging
  #       uses: azure/webapps-deploy@v3
  #       with:
  #         app-name: 'webapp-lab-random'
  #         slot-name: 'staging'
  #         package: .
=======
  # Temporarily disabled staging deployment due to identity federation issue
  # Uncomment and configure when identity federation is set up for staging branch
  # deploy-staging:
  #   runs-on: ubuntu-latest
  #   needs: build
  #   if: github.ref == 'refs/heads/staging'
  #   permissions:
  #     id-token: write
  #     contents: read

  #   steps:
  #     - name: Download artifact from build job
  #       uses: actions/download-artifact@v4
  #       with:
  #         name: node-app

  #     - name: Login to Azure
  #       uses: azure/login@v2
  #       with:
  #         client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_97423809BDD846D0A76B0B3BFC35A027 }}
  #         tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_F37A58B16D544F19B99C25F8E9715A09 }}
  #         subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_9B15030317A34B218C9745750F662EF7 }}

  #     - name: Deploy to Azure Web App (Staging)
  #       id: deploy-to-staging
  #       uses: azure/webapps-deploy@v3
  #       with:
  #         app-name: 'webapp-lab-random'
  #         slot-name: 'staging'
  #         package: .
>>>>>>> staging
